# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cookie_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'cookie_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ookie_service.proto\x12\x06\x63ookie\"\"\n\x11\x43ookieRequest_Add\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"#\n\x13\x43ookieRequest_Query\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x14\x43ookieRequest_Delete\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x12\x43ookieRequest_Test\" \n\x12\x43ookieRequest_ByID\x12\n\n\x02id\x18\x01 \x01(\x05\"1\n\x0e\x43ookieResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x13\x43ookieResponse_ByID\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"$\n\x14\x43ookieRequest_ByName\x12\x0c\n\x04name\x18\x01 \x01(\t\"2\n\x15\x43ookieResponse_ByName\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"&\n\x15\x43ookieRequest_ByEmail\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"=\n\x16\x43ookieResponse_ByEmail\x12#\n\x07\x63ookies\x18\x01 \x03(\x0b\x32\x12.cookie.CookieInfo\"&\n\nCookieInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2\x89\x04\n\rCookieService\x12>\n\tAddCookie\x12\x19.cookie.CookieRequest_Add\x1a\x16.cookie.CookieResponse\x12\x44\n\x0c\x44\x65leteCookie\x12\x1c.cookie.CookieRequest_Delete\x1a\x16.cookie.CookieResponse\x12\x42\n\x0bQueryCookie\x12\x1b.cookie.CookieRequest_Query\x1a\x16.cookie.CookieResponse\x12@\n\nTestCookie\x12\x1a.cookie.CookieRequest_Test\x1a\x16.cookie.CookieResponse\x12H\n\rGetCookieByID\x12\x1a.cookie.CookieRequest_ByID\x1a\x1b.cookie.CookieResponse_ByID\x12N\n\x0fGetCookieByName\x12\x1c.cookie.CookieRequest_ByName\x1a\x1d.cookie.CookieResponse_ByName\x12R\n\x11GetCookiesByEmail\x12\x1d.cookie.CookieRequest_ByEmail\x1a\x1e.cookie.CookieResponse_ByEmailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cookie_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COOKIEREQUEST_ADD']._serialized_start=32
  _globals['_COOKIEREQUEST_ADD']._serialized_end=66
  _globals['_COOKIEREQUEST_QUERY']._serialized_start=68
  _globals['_COOKIEREQUEST_QUERY']._serialized_end=103
  _globals['_COOKIEREQUEST_DELETE']._serialized_start=105
  _globals['_COOKIEREQUEST_DELETE']._serialized_end=141
  _globals['_COOKIEREQUEST_TEST']._serialized_start=143
  _globals['_COOKIEREQUEST_TEST']._serialized_end=163
  _globals['_COOKIEREQUEST_BYID']._serialized_start=165
  _globals['_COOKIEREQUEST_BYID']._serialized_end=197
  _globals['_COOKIERESPONSE']._serialized_start=199
  _globals['_COOKIERESPONSE']._serialized_end=248
  _globals['_COOKIERESPONSE_BYID']._serialized_start=250
  _globals['_COOKIERESPONSE_BYID']._serialized_end=300
  _globals['_COOKIEREQUEST_BYNAME']._serialized_start=302
  _globals['_COOKIEREQUEST_BYNAME']._serialized_end=338
  _globals['_COOKIERESPONSE_BYNAME']._serialized_start=340
  _globals['_COOKIERESPONSE_BYNAME']._serialized_end=390
  _globals['_COOKIEREQUEST_BYEMAIL']._serialized_start=392
  _globals['_COOKIEREQUEST_BYEMAIL']._serialized_end=430
  _globals['_COOKIERESPONSE_BYEMAIL']._serialized_start=432
  _globals['_COOKIERESPONSE_BYEMAIL']._serialized_end=493
  _globals['_COOKIEINFO']._serialized_start=495
  _globals['_COOKIEINFO']._serialized_end=533
  _globals['_COOKIESERVICE']._serialized_start=536
  _globals['_COOKIESERVICE']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
